### ISSUE TITLE
Thanks for your work

### ISSUE THREAD

**Issue by UniMa007** [opendata-for-all/openapi-metamodel#22]
Hello Hamza,

Thanks for your work and your open source contribution to an OpenAPI 3 meta model.
Such a metamodel can be very useful for M2M transformations of APIs, thus potentially bridging the GAP between "TransferObjects" and "Business Objects" in a very rigorous way.

Do you have a link to buy you a beer? :)

Regards,

M.

**Comment by hamzaed** [comment]
Hi,

I'm glad you like our work. The OpenAPI 3 metamodel is located under the branch [https://github.com/opendata-for-all/openapi-metamodel/tree/OpenAPI3](OpenAPI3) and soon will be integrated with the rest of the tools which include mature support for OpenAPI 2. 

Thanks for the beer offer. We may think about joining the Github sponsors program in the future to allow people to support us.

Regards, 

Hamza

**Comment by UniMa007** [comment]
I'm very much looking forward to it, thanks
