### ISSUE TITLE
Unable to Run the project

### ISSUE THREAD

**Issue by dkarthi1973** [opendata-for-all/openapi-metamodel#27]
I have tried to execute and see the report ( i.e mvn test) but no output generated in that project. could you please let me know the procedure or commands for testing this model.

**Comment by hamzaed** [comment]
You can't run the tests using `mvn test`. You should use `mvn verify` instead. We rely on Tycho to bundle the project. Tycho executes the tests in an OSGi container using the `tycho-surefire-plugin` plugin. Such tests are executed in the integration test phase (after the package phase which creates the bundles).
